# AUTOGENERATED! DO NOT EDIT! File to edit: ../src/functions/helper.ipynb.

# %% auto 0
__all__ = ['convert_true_false']

# %% ../src/functions/helper.ipynb 2
def convert_true_false(true_false):
    
    if true_false == True or true_false == False:
        return true_false
    elif true_false == "True":
        return True
    elif true_false == "False":
        return False
    else:
        raise ValueError("Please enter either True or False")
