# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mmon-gcm2',
                'doc_host': 'https://noahsprent.github.io',
                'git_url': 'https://github.com/noahsprent/mmon-gcm2',
                'lib_path': 'mmon_gcm2'},
  'syms': {'mmon_gcm2.core': {'mmon_gcm2.core.foo': ('core.html#foo', 'mmon_gcm2/core.py')}}}
